name: discord-job-bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r requirements.txt

      - name: Verify JobSpy install
        run: |
          python - <<'PY'
          import importlib.util, sys
          spec = importlib.util.find_spec("jobspy")
          if not spec:
              sys.exit("❌  jobspy NOT importable")
          import jobspy, inspect, pathlib
          print("✅  jobspy located at", pathlib.Path(jobspy.__file__))
          print("   version:", getattr(jobspy, "__version__", "unknown"))
          print("   scrape_jobs present:", hasattr(jobspy, "scrape_jobs"))
          PY

      - name: Run the bot
        env:
          TOKEN:               ${{ secrets.TOKEN }}
          FT_CHANNEL_ID:       ${{ secrets.FT_CHANNEL_ID }}
          INTERN_CHANNEL_ID:   ${{ secrets.INTERN_CHANNEL_ID }}
          SWE:                 ${{ secrets.SWE }}
          ENG:                 ${{ secrets.ENG }}
          DATA:                ${{ secrets.DATA }}
          PM:                  ${{ secrets.PM }}
          SUM26:               ${{ secrets.SUM26 }}
          SUM25:               ${{ secrets.SUM25 }}
          OS26:                ${{ secrets.OS26 }}
          OS25:                ${{ secrets.OS25 }}
          SCRAPE_GITHUB:       ${{ secrets.SCRAPE_GITHUB }}
          SCRAPE_JOBSPY:       ${{ secrets.SCRAPE_JOBSPY }}
          SCRAPE_MIN:          ${{ secrets.SCRAPE_MIN }}
          DATABASE_URL:        ${{ secrets.DATABASE_URL }}
        run: python bot.py
