name: Run Discord Job Bot every 30 min

on:
  schedule:
    # every 30 minutes (UTC)
    - cron: "*/30 * * * *"
  workflow_dispatch:   # manual run
  push:
    branches: [ main ] # on any push to main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Verify jobspy is on path
      run: |
        python - <<'PY'
        import sys, importlib.util, pathlib, textwrap, inspect
        print("="*60)
        print("Python:", sys.version)
        print("sys.executable:", sys.executable)
        print("sys.path:")
        for p in sys.path:
            print("  ", p)
        spec = importlib.util.find_spec("jobspy")
        print("\njobspy spec →", spec)
        if not spec:
            print("!! jobspy NOT FOUND !!")
            sys.exit(1)
        import jobspy
        print("jobspy file →", pathlib.Path(jobspy.__file__))
        print("jobspy version →", getattr(jobspy, "__version__", "unknown"))
        print("="*60)
        PY

    - name: Run Discord Job Bot
      env:
        TOKEN:             ${{ secrets.TOKEN }}
        FT_CHANNEL_ID:     ${{ secrets.FT_CHANNEL_ID }}
        INTERN_CHANNEL_ID: ${{ secrets.INTERN_CHANNEL_ID }}

        SWE:   ${{ secrets.SWE }}
        ENG:   ${{ secrets.ENG }}
        DATA:  ${{ secrets.DATA }}
        PM:    ${{ secrets.PM }}
        SUM26: ${{ secrets.SUM26 }}
        SUM25: ${{ secrets.SUM25 }}
        OS26:  ${{ secrets.OS26 }}
        OS25:  ${{ secrets.OS25 }}

        SCRAPE_GITHUB: ${{ secrets.SCRAPE_GITHUB }}
        SCRAPE_JOBSPY: ${{ secrets.SCRAPE_JOBSPY }}
        SCRAPE_MIN:    ${{ secrets.SCRAPE_MIN }}

        DATABASE_URL:  ${{ secrets.DATABASE_URL }}
      run: |
        echo "Starting Discord Job Bot at $(date -u)"
        python bot.py
